# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[(1, 'Android Developer'), (2, 'Designer'), (3, 'Java Developer'), (4, 'PHP Developer'), (5, 'Python Developer'), (6, 'Rails Developer'), (7, 'WordPress Developer'), (8, 'iOS Developer')], default='', max_length=100),
        ),
    ]
