# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170407_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='needs',
            field=models.ManyToManyField(to='projects.Skill'),
        ),
    ]
