# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170407_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='completed',
        ),
        migrations.AddField(
            model_name='application',
            name='for_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
