# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170407_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('1', 'Android Developer'), ('2', 'Designer'), ('3', 'Java Developer'), ('4', 'PHP Developer'), ('5', 'Python Developer'), ('6', 'Rails Developer'), ('7', 'WordPress Developer'), ('8', 'iOS Developer')], default='', max_length=1),
        ),
    ]
