# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
    ]
