# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0002_auto_20170403_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(related_name='skills', to='projects.Skill'),
        ),
    ]
