# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170406_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skill',
            new_name='skills',
        ),
    ]
